### ISSUE TITLE
Multiple Issues on WinOS

### ISSUE THREAD

**Issue by Hedrauta** [jojotastic777/bitburner-bbpm#1]
So..... you should write, what requrements are used in your Readme.md

- I tried to get it to run on WInos... which took me a bit, to figure out and install yarn...
- then I saw a "wget" ... which doesn't work on Win.... even PowerShell doesn't have a wget cmdlet 
- what is tsc? Do I need to install some kind of Node-module for Typescript?

....

**Comment by jojotastic777** [comment]
I've added some better documentation to the README. If you still are having problems after reading it, let me know and I'll re-open this issue.

**Comment by Hedrauta** [comment]
👍
